# Generated by Django 5.1.5 on 2025-02-04 17:40

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='refreshtoken',
            name='expires_at',
            field=models.DateField(default=datetime.datetime(2025, 3, 6, 17, 40, 10, 500661, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='refreshtoken',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
