# Generated by Django 5.1.5 on 2025-02-04 17:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0002_refreshtoken_expires_at_alter_refreshtoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refreshtoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 6, 17, 50, 35, 978097, tzinfo=datetime.timezone.utc)),
        ),
    ]
